apiVersion: v1
kind: Pod
metadata:
  name: interactive-rw-gpu
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/zihaozhou/nautilus_tutorial:jupyterhub
    command: ["jupyter", "lab", "--NotebookApp.token=627a7b3b"]
    volumeMounts:
    - mountPath: /Results
      name: mia-rw
    resources:
      limits:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "4"
  restartPolicy: Never
  volumes:
    - name: mia-rw
      persistentVolumeClaim:
        claimName: mia-rw
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-RTX-A6000
